const A={overview:null,profile:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('vi-VN').format(Number(n||0));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=$('#adminToast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
async function api(url,opt={}){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(r.status===401){location.href='/';throw new Error('Phiên đăng nhập đã hết hạn')}if(r.status===403&&url.includes('/api/admin/')){location.href='/app';throw new Error(d.detail||'Không có quyền ADMIN')}if(!r.ok)throw new Error(d.detail||'Có lỗi xảy ra');return d}
function who(x){return x.display_name||x.email||('User #'+x.user_id)}
function time(x){if(!x)return 'Chưa có';const d=new Date(x.includes('T')?x:x.replace(' ','T')+'Z');return isNaN(d)?x:d.toLocaleString('vi-VN')}
function empty(text){return `<div class="empty-admin">${esc(text)}</div>`}
function setView(name){$$('.admin-nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.admin-view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));const titles={overview:'Tổng quan doanh nghiệp',staff:'Nhân viên',data:'Dữ liệu & AI Learning',projects:'Dự án Marketing',activity:'Nhật ký hoạt động',settings:'Mã doanh nghiệp'};$('#pageTitle').textContent=titles[name]||'ADMIN';if(name==='staff')loadStaff();if(name==='activity')loadActivity();}
$$('.admin-nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));

function renderActivity(items,target){const e=$(target);if(!items?.length){e.innerHTML=empty('Chưa có hoạt động được ghi nhận.');return}e.innerHTML=items.map(x=>`<div class="activity-item"><div class="activity-avatar">${esc((who(x)[0]||'U').toUpperCase())}</div><div><b>${esc(x.action)}</b><p>${esc(who(x))}${x.details?' · '+esc(x.details):''}</p></div><time>${esc(time(x.created_at))}</time></div>`).join('')}
function renderSimple(items,target,type){const e=$(target);if(!items?.length){e.innerHTML=empty(type==='dataset'?'Chưa có bộ dữ liệu.':'Chưa có dự án marketing.');return}e.innerHTML=items.map(x=>type==='dataset'?`<div class="simple-item"><div><b>${esc(x.upload_name)}</b><p>${esc(who(x))} · ${esc(time(x.uploaded_at))}</p></div><strong>${fmt(x.record_count)} dòng</strong></div>`:`<div class="simple-item"><div><b>${esc(x.scenario_text||'Chiến dịch')}</b><p>${esc(who(x))}</p></div><strong>${esc(x.star_rating||0)}/5</strong></div>`).join('')}
async function loadOverview(){const d=await api('/api/admin/overview');A.overview=d;$('#orgName').textContent=d.organization||'Doanh nghiệp';$('#kStaff').textContent=fmt(d.staff.total);$('#kActive').textContent=`${fmt(d.staff.enabled)} đang hoạt động · ${fmt(d.staff.active_today)} có hoạt động hôm nay`;$('#kProjects').textContent=fmt(d.projects);$('#kCustomers').textContent=fmt(d.customers);$('#kDatasets').textContent=`${fmt(d.datasets)} bộ dữ liệu`;$('#kTwins').textContent=fmt(d.digital_twins);$('#kPersonas').textContent=`${fmt(d.personas)} persona · ${fmt(d.segments)} nhóm`;$('#kResponses').textContent=fmt(d.simulation_responses);$('#kScore').textContent=`Điểm TB ${d.avg_score||0}/10`;$('#kLearning').textContent=fmt(d.confirmed_learning);$('#kReal').textContent=`REAL ${d.real_data_pct||0}%`;for(const [id,key] of [['buy','buy'],['hesitate','hesitate'],['no','not_buy']]){$('#'+id+'Pct').textContent=(d.purchase_intent[key]?.pct||0)+'%';$('#'+id+'Count').textContent=fmt(d.purchase_intent[key]?.count||0)+' phản hồi'}renderActivity(d.recent_activity,'#recentActivity');renderSimple(d.recent_datasets,'#recentDatasets','dataset');renderSimple(d.recent_projects,'#recentProjects','project');$('#dataDatasets').textContent=fmt(d.datasets);$('#dataCustomers').textContent=fmt(d.customers);$('#dataLearning').textContent=fmt(d.confirmed_learning);renderSimple(d.recent_datasets,'#dataList','dataset');$('#projectCount').textContent=fmt(d.projects);$('#projectTwins').textContent=fmt(d.digital_twins);$('#projectScore').textContent=d.avg_score||0;renderSimple(d.recent_projects,'#projectList','project')}
async function loadProfile(){const d=await api('/api/admin/profile');A.profile=d;$('#adminName').textContent=d.display_name||'ADMIN';$('#adminEmail').textContent=d.email||'';$('#joinCode').textContent=d.join_code||'Chưa có mã';if(d.organization_name)$('#orgName').textContent=d.organization_name}
async function loadStaff(){const d=await api('/api/admin/staff'),body=$('#staffBody');if(!d.items?.length){body.innerHTML=`<tr><td colspan="7">${empty('Chưa có nhân viên. Hãy cấp mã doanh nghiệp để nhân viên đăng ký.')}</td></tr>`;return}body.innerHTML=d.items.map(x=>`<tr><td class="employee-cell"><b>${esc(x.display_name||'Chưa đặt tên')}</b><small>${esc(x.email)}</small></td><td><span class="mini-status ${x.is_active?'ok':'off'}">${x.is_active?'Đang hoạt động':'Đã khóa'}</span></td><td>${fmt(x.datasets)}</td><td>${fmt(x.projects)}</td><td>${fmt(x.responses)}</td><td>${esc(time(x.last_activity))}</td><td><div class="row-actions"><button class="secondary" onclick="showEmployee(${x.id})">Chi tiết</button><button class="${x.is_active?'secondary':'primary'}" onclick="toggleEmployee(${x.id},${x.is_active?0:1})">${x.is_active?'Khóa':'Mở'}</button></div></td></tr>`).join('')}
window.showEmployee=async id=>{const d=await api('/api/admin/staff/'+id),e=$('#staffDetail'),u=d.employee;e.classList.remove('hidden');e.innerHTML=`<div class="card-title"><div><h3>${esc(u.display_name||u.email)}</h3><p>${esc(u.email)} · Tạo ${esc(time(u.created_at))}</p></div><button class="text-btn" onclick="document.querySelector('#staffDetail').classList.add('hidden')">Đóng</button></div><div class="detail-grid"><div class="detail-box"><span>Dataset</span><b>${fmt(d.datasets.length)}</b></div><div class="detail-box"><span>Dự án</span><b>${fmt(d.projects.length)}</b></div><div class="detail-box"><span>Hoạt động gần đây</span><b>${fmt(d.activity.length)}</b></div></div><h4>Nhật ký gần đây</h4><div class="activity-list">${d.activity.length?d.activity.slice(0,12).map(x=>`<div class="simple-item"><div><b>${esc(x.action)}</b><p>${esc(time(x.created_at))}</p></div><strong>${esc(x.status_code||'')}</strong></div>`).join(''):empty('Chưa có hoạt động')}</div>`;e.scrollIntoView({behavior:'smooth',block:'start'})}
window.toggleEmployee=async(id,active)=>{if(!confirm(active?'Mở lại tài khoản nhân viên này?':'Khóa tài khoản này? Nhân viên sẽ bị đăng xuất.'))return;await api(`/api/admin/staff/${id}/active`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!!active})});toast(active?'Đã mở tài khoản':'Đã khóa tài khoản');await Promise.all([loadStaff(),loadOverview()])}
async function loadActivity(){const d=await api('/api/admin/activity?limit=300');renderActivity(d.items,'#activityFull')}
$('#refreshActivity').onclick=loadActivity;$('#copyCode').onclick=async()=>{await navigator.clipboard.writeText($('#joinCode').textContent);toast('Đã sao chép mã doanh nghiệp')};$('#regenerateCode').onclick=async()=>{if(!confirm('Tạo mã mới? Mã cũ sẽ không dùng để đăng ký nhân viên mới được nữa.'))return;const d=await api('/api/admin/join-code/regenerate',{method:'POST'});$('#joinCode').textContent=d.join_code;toast('Đã tạo mã mới')};$('#logoutBtn').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'};
(async()=>{try{const me=await api('/api/auth/me');if(me.role!=='admin'){location.href='/app';return}await Promise.all([loadProfile(),loadOverview()]);}catch(e){console.error(e);toast(e.message)}})();
